apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gh-monit.fullname" . }}-secret
  labels:
    {{- include "gh-monit.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secretEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
