apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-monit
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: gh-monit
  template:
    spec:
      containers:
        - name: gh-monit
          image: gravitate-registry.cr.de-fra.ionos.com/gh-monit:latest
          env:
          - name: BASE_URL
            value: https://gravitate-health.lst.tfo.upm.es/
          resources: {}